language: haskell

ghc:
  - 7.4.2
  - 7.6.3

before_install:
  - sudo apt-get -q -y install hlint || cabal install hlint

script:
  - hlint . --ignore="Parse error"
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build
  - cabal install
  - run-cabal-test --show-details=always
  - cabal check
  - cabal sdist

after_script:
  - hpc-coveralls test-all

notifications:
  webhooks:
  urls:
    - https://webhooks.gitter.im/e/19a86836a14769ac4b51
  on_success: change
  on_failure: always
  on_start: false
