env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.1

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal-1.18 update
  - travis_retry sudo apt-get -q -y install hlint || cabal-1.18 install hlint
  - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks

script:
  - hlint . --ignore="Parse error"
  - cabal-1.18 configure --enable-tests --enable-benchmarks --enable-library-coverage -v2
  - cabal-1.18 build
  - |
    if [ $GHCVER = "7.8.1" ]; then
      cabal-1.18 test --show-details=always
    else
      dist/build/run-cabal-test/run-cabal-test --cabal-name=cabal-1.18 --show-details=always
    fi
  - cabal-1.18 check
  - cabal-1.18 sdist
  - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
    (cd dist/;
    if [ -f "$SRC_TGZ" ]; then
      cabal-1.18 install "$SRC_TGZ";
    else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
    fi)

after_script:
  - dist/build/hpc-coveralls/hpc-coveralls --display-report test-all

notifications:
  webhooks:
  urls:
    - https://webhooks.gitter.im/e/19a86836a14769ac4b51
  on_success: change
  on_failure: always
  on_start: false
